services:
  # A Docker web service
  - type: web
    name: pr-review-agent
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    # Specify the plan (remove this if you're using a different plan)
    plan: starter
    # Set auto-deploy to true if you want automatic deployments
    autoDeploy: true
    # Healthcheck path
    healthCheckPath: /
    # Environment variables
    envVars:
      - key: PORT
        value: 8000
      # Add any other environment variables your app needs